const data = [
  {
    chat_id: 1,
    customer_id: 5,
    question: 'Can you explain the average salary progression for employees in this department? ',
    topic: 'salary',
    keywords: 'average salary progression employee department',
    response: 'The average salary is 126307 - 144369 (USD).',
    rating: 0,
    created_at: '2023-09-22 07:23:30',
  },
  {
    chat_id: 1,
    customer_id: 5,
    question: 'Can you explain the average salary progression for employees in this department? ',
    topic: 'salary',
    keywords: 'average salary progression employee department',
    response: 'The average salary is 126307 - 144369 (USD).',
    rating: 1,
    created_at: '2023-09-22 07:23:30',
  },
  {
    chat_id: 1,
    customer_id: 5,
    question: 'Can you explain the average salary progression for employees in this department? ',
    topic: 'amount',
    keywords: 'average salary progression employee department',
    response: 'The average salary is 126307 - 144369 (USD).',
    rating: 2,
    created_at: '2023-09-22 07:23:30',
  },
  {
    chat_id: 1,
    customer_id: 5,
    question: 'Can you explain the average salary progression for employees in this department? ',
    topic: 'amount',
    keywords: 'average salary progression employee department',
    response: 'The average salary is 126307 - 144369 (USD).',
    rating: 3,
    created_at: '2023-09-22 07:23:30',
  },
  {
    chat_id: 1,
    customer_id: 5,
    question: 'Can you explain the average salary progression for employees in this department? ',
    topic: 'trivia',
    keywords: 'average salary progression employee department',
    response: 'The average salary is 126307 - 144369 (USD).',
    rating: 4,
    created_at: '2023-09-22 07:23:30',
  },
  {
    chat_id: 1,
    customer_id: 5,
    question: 'Can you explain the average salary progression for employees in this department? ',
    topic: 'salary',
    keywords: 'average salary progression employee department',
    response: 'The average salary is 126307 - 144369 (USD).',
    rating: 5,
    created_at: '2023-09-22 07:23:30',
  },
  {
    chat_id: 1,
    customer_id: 5,
    question: 'Can you explain the average salary progression for employees in this department? ',
    topic: 'trivia',
    keywords: 'average salary progression employee department',
    response: 'The average salary is 126307 - 144369 (USD).',
    rating: 0,
    created_at: '2023-09-22 07:23:30',
  },
  {
    chat_id: 1,
    customer_id: 5,
    question: 'Can you explain the average salary progression for employees in this department? ',
    topic: 'salary',
    keywords: 'average salary progression employee department',
    response: 'The average salary is 126307 - 144369 (USD).',
    rating: 0,
    created_at: '2023-09-22 07:23:30',
  },
]

export default data
