const data = [
  {
    id: 1,
    customer_id: 5,
    keyword: '',
    industry: 'IT',
    language: '',
    location: '',
    salary: '',
    search_time: '2023-09-22 07:23:30',
  },
  {
    id: 2,
    customer_id: 4,
    keyword: 'C#',
    industry: 'IT',
    language: '',
    location: '',
    salary: '',
    search_time: '2023-09-22 07:23:30',
  },
  {
    id: 3,
    customer_id: 5,
    keyword: 'BA',
    industry: '',
    language: '',
    location: '',
    salary: '',
    search_time: '2023-09-22 07:23:30',
  },
  {
    id: 4,
    customer_id: 5,
    keyword: '',
    industry: 'Services',
    language: 'English',
    location: '',
    salary: '',
    search_time: '2023-09-22 07:23:30',
  },
  {
    id: 5,
    customer_id: 3,
    keyword: '',
    industry: 'IT',
    language: '',
    location: '',
    salary: '',
    search_time: '2023-09-22 07:23:30',
  },
  {
    id: 6,
    customer_id: 3,
    keyword: '',
    industry: 'IT',
    language: '',
    location: 'HCM',
    salary: '',
    search_time: '2023-09-22 07:23:30',
  },
  {
    id: 7,
    customer_id: 7,
    keyword: 'manager',
    industry: '',
    language: '',
    location: '',
    salary: '1000-1500',
    search_time: '2023-09-22 07:23:30',
  },
  {
    id: 8,
    customer_id: 9,
    keyword: '',
    industry: 'IT',
    language: '',
    location: '',
    salary: '',
    search_time: '2023-09-22 07:23:30',
  },
]

export default data
